#!/bin/sh
# AUTHOR: arthur@arthurbais.xyz
#
# DATE: 09/07/20
#
# DESC: Elvi to search searx
# elvis: searx		-- Use one of the instances of searx (https://searx.privatenet.cf/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Searx search instance (https://searx.privatenet.cf/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://searx.privatenet.cf/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://searx.privatenet.cf/?q=${escaped_args}"
fi
