#!/bin/sh
# AUTHOR: arthur@arthurbais.xyz
#
# DATE: 09/07/20
#
# DESC: Elvi to search searx tor instance
# elvis: torsearx		-- Use one of the instances of searx (http://z5vawdol25vrmorm4yydmohsd4u6rdoj2sylvoi3e3nqvxkvpqul7bqd.onion/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Searx search instance (http://z5vawdol25vrmorm4yydmohsd4u6rdoj2sylvoi3e3nqvxkvpqul7bqd.onion/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://z5vawdol25vrmorm4yydmohsd4u6rdoj2sylvoi3e3nqvxkvpqul7bqd.onion/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://z5vawdol25vrmorm4yydmohsd4u6rdoj2sylvoi3e3nqvxkvpqul7bqd.onion/?q=${escaped_args}"
fi
